StartupEvents.registry('item', event => {
    event.create('tech_gear')
    .displayName('§d§lTECH GEAR')
    .tooltip('§d工業の高み')
    .unstackable()
    .glow(true)
    event.create(`ae_coin`)
    .displayName('§d§lAE2 Coin')
    .tooltip('§dストレージの汎用性')
    .unstackable()
    .glow(true)
    event.create(`mek_board`)
    .displayName('§d§lMekanism Board')
    .tooltip('§dかなりの技術が詰まった板')
    .unstackable()
    .glow(true)
})